name: Build VCV Rack Plugin

on:
  push:
    branches: [ main, master ]

jobs:
  build-mac:
    name: Build for Mac
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4


    - name: Download VCV Rack SDK
      run: |
        curl -L "https://vcvrack.com/downloads/Rack-SDK-2.4.0-mac-x64%2Barm64.zip" -o sdk.zip
        unzip sdk.zip
        # Находим папку SDK и переименовываем ее в просто "Rack-SDK" для порядка
        mv Rack-SDK-* Rack-SDK || true


    - name: Compile Plugin
      run: |
        export RACK_DIR=$PWD/Rack-SDK
        make clean
        make dist

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Neiroi-Mac-Plugin
        path: dist/*.vcvplugin
